[project]
name = 'aibtcdev-smart-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.aibtcdev-aibtc]
path = 'contracts/aibtcdev-aibtc.clar'
clarity_version = 2
epoch = 2.4

[contracts.aibtcdev-bank-account]
path = 'contracts/aibtcdev-bank-account.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-resources-v1]
path = 'contracts/aibtcdev-resources-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.aibtcdev-traits-v1]
path = 'contracts/aibtcdev-traits-v1.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
